#!/usr/bin/env sh

# Prevent scriptting addition issue
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Set the default layout to bsp
yabai -m config window_placement second_child

# Border color
borders active_color=0xff9d7cd8 inactive_color=0x4fbb9af7 width=5.0 &

yabai -m config external_bar    all:32:0
yabai -m config layout          bsp
yabai -m config top_padding     12
yabai -m config bottom_padding  12
yabai -m config left_padding    12
yabai -m config right_padding   12
yabai -m config window_gap      12

# Center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt

# Set modifier + left-click drag to move window
yabai -m config mouse_action1 move

# Set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap

# Unmanagable windows
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^About this Mac$" manage=off
yabai -m rule --add app="^AWS VPN Client$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^League of Legends$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off

# Naming spaces
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 7 --label seven
yabai -m space 8 --label eight
yabai -m space 9 --label nine
yabai -m space 10 --label ten

# Windows opacity
yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

# Remove window bar
yabai -m config menubar_opacity 0.0
